/* eslint-disable */
require('./angle-short')
require('./angle-wide')
require('./chevron-right')
require('./hexagon')
require('./line-curve')
require('./line-sharp')
require('./square')
require('./squares')
require('./triangle-large')
require('./triangle')
