/* tslint:disable */
import './angle-short'
import './angle-wide'
import './chevron-right'
import './hexagon'
import './line-curve'
import './line-sharp'
import './square'
import './squares'
import './triangle-large'
import './triangle'
